### ISSUE TITLE
'Always Close Current Profile' Option Issue

### ISSUE THREAD

**Issue by BashBandito** [dillenger/profile-switcher#3]
Hi,

Thank you for developing and maintaining this fantastic add-on that so many of us appreciate.

I’ve encountered a bug that I hope you might consider addressing. The 'always close current profile' option in the profile switcher isn’t working as expected when the Thunderbird add-on 'Minimize on Close' is installed and enabled. It seems that the 'always close current profile' option mimics the behavior of clicking the X on the Thunderbird window, which causes it to minimize instead of closing, due to the 'Minimize on Close' extension.

If possible, could this option be adjusted to replicate the 'Quit' function (accessible via Ctrl+Q or from the hamburger menu) instead? This change might ensure that it works harmoniously with the 'Minimize on Close' extension.

As a Linux user, I’m aware that not all distributions support tray icon add-ons, so I rely on this minimize-to-tray extension. Currently, when attempting to switch profiles, it minimizes rather than closing the current profile, which is quite problematic.

Thank you for considering this request.

**Comment by dillenger** [comment]
Hi,

Thanks for using this add-on.
I think I fixed it, the add-on now closes all windows when switching.
Including messages opened in separate windows, which was a problem before.

Can you test it for me? 
Just download the zip, extract it to a folder, re-zip the contents of that folder and use that as an installer.
Or give me an email adress where I can send a beta version.

Cheers,

Michel

**Comment by BashBandito** [comment]
Hi,

Thank you for the quick response and action.

I went ahead and tested the add-on as you instructed and am very pleased to say that it is indeed working.

Thank you so much for doing this. Greatly appreciated!

**Comment by dillenger** [comment]
You're welcome.

**Comment by BashBandito** [comment]
Hello again,

I have a question about Betterbird. I tried installing the updated zip file from the GitHub repo with the fix we discussed, but Betterbird gave me an error: “This extension does not support Betterbird 115.9.0.”

Since I couldn't use the updated version, I ended up installing the older Profile Switcher from the Thunderbird add-ons page, which still has the bug.

When the updated add-on with the bug fix is officially released, will it be compatible with Betterbird 115.9.0? I can't update Betterbird until the package maintainer updates it manually, which might take some time—such is the life of NixOS.

**Comment by dillenger** [comment]
No, there will be no more new versions supporting either Thunderbird 115.* or Betterbird 115.*
You'll have to wait for Betterbird 128.
PS, despite Betterbird claiming to be a drop-in replacement for Thunderbird it is **not** a good idea to share a profile between Thunderbird and Betterbird.

**Comment by BashBandito** [comment]
> No, there will be no more new versions supporting either Thunderbird 115.* or Betterbird 115.* You'll have to wait for Betterbird 128. PS, despite Betterbird claiming to be a drop-in replacement for Thunderbird it is **not** a good idea to share a profile between Thunderbird and Betterbird.

I understand, I'll find an alternative solution until Betterbird 128 is released.

This is for a separate system btw, I don't share profiles between the two applications on the same system. I have done that in the past, and it was always a mess, therefore I agree with your advice.

Thanks again.
